# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ohdsi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ohdsi.proto',
  package='cdmv5',
  serialized_pb=_b('\n\x0bohdsi.proto\x12\x05\x63\x64mv5\"\xc6\x02\n\tCondition\x12\x1f\n\x17\x43ONDITION_OCCURRENCE_ID\x18\x01 \x02(\x05\x12\x11\n\tPERSON_ID\x18\x02 \x02(\x05\x12\x1c\n\x14\x43ONDITION_CONCEPT_ID\x18\x03 \x02(\x05\x12\x1c\n\x14\x43ONDITION_START_DATE\x18\x04 \x02(\x05\x12\x1a\n\x12\x43ONDITION_END_DATE\x18\x05 \x02(\x05\x12!\n\x19\x43ONDITION_TYPE_CONCEPT_ID\x18\x06 \x02(\x05\x12\x13\n\x0bSTOP_REASON\x18\x07 \x02(\x05\x12\x13\n\x0bPROVIDER_ID\x18\x08 \x02(\x05\x12\x1b\n\x13VISIT_OCCURRENCE_ID\x18\t \x02(\x05\x12\x1e\n\x16\x43ONDITION_SOURCE_VALUE\x18\n \x02(\x05\x12#\n\x1b\x43ONDITION_SOURCE_CONCEPT_ID\x18\x0b \x02(\x05\"(\n\x0c\x44rugExposure\x12\x18\n\x10\x44RUG_EXPOSURE_ID\x18\x01 \x02(\x05\"\x0b\n\tProcedure\"\x94\x01\n\x05Visit\x12\x1b\n\x13VISIT_OCCURRENCE_ID\x18\x01 \x02(\x05\x12\"\n\x05\x64rugs\x18\x02 \x03(\x0b\x32\x13.cdmv5.DrugExposure\x12$\n\nconditions\x18\x03 \x03(\x0b\x32\x10.cdmv5.Condition\x12$\n\nprocedures\x18\x04 \x03(\x0b\x32\x10.cdmv5.Procedure\"\xe2\x03\n\x06Person\x12\x11\n\tperson_id\x18\x01 \x02(\t\x12\x15\n\ryear_of_birth\x18\x02 \x02(\x05\x12\x16\n\x0emonth_of_birth\x18\x03 \x02(\x05\x12\x14\n\x0c\x64\x61y_of_birth\x18\x04 \x02(\x05\x12\x15\n\rtime_of_birth\x18\x05 \x02(\x05\x12\x0c\n\x04race\x18\x06 \x02(\x05\x12\x0e\n\x06gender\x18\x07 \x02(\x05\x12\x11\n\tethnicity\x18\x08 \x02(\x05\x12\x13\n\x0blocation_id\x18\t \x02(\x05\x12\x13\n\x0bprovider_id\x18\n \x02(\x05\x12\x14\n\x0c\x63\x61re_site_id\x18\x0b \x02(\x05\x12\x1b\n\x13gender_source_value\x18\x0c \x02(\x05\x12 \n\x18gender_source_concept_id\x18\r \x02(\x05\x12\x19\n\x11race_source_value\x18\x0e \x02(\x05\x12\x1e\n\x16race_source_concept_id\x18\x0f \x02(\x05\x12#\n\x1b\x65thnicity_source_concept_id\x18\x10 \x02(\x05\x12\x1e\n\x16\x65thnicity_source_value\x18\x11 \x02(\x05\x12\x1b\n\x13person_source_value\x18\x12 \x02(\x05\x12\x1c\n\x06visits\x18\x13 \x03(\x0b\x32\x0c.cdmv5.Visit')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='cdmv5.Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CONDITION_OCCURRENCE_ID', full_name='cdmv5.Condition.CONDITION_OCCURRENCE_ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PERSON_ID', full_name='cdmv5.Condition.PERSON_ID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CONDITION_CONCEPT_ID', full_name='cdmv5.Condition.CONDITION_CONCEPT_ID', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CONDITION_START_DATE', full_name='cdmv5.Condition.CONDITION_START_DATE', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CONDITION_END_DATE', full_name='cdmv5.Condition.CONDITION_END_DATE', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CONDITION_TYPE_CONCEPT_ID', full_name='cdmv5.Condition.CONDITION_TYPE_CONCEPT_ID', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='STOP_REASON', full_name='cdmv5.Condition.STOP_REASON', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PROVIDER_ID', full_name='cdmv5.Condition.PROVIDER_ID', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VISIT_OCCURRENCE_ID', full_name='cdmv5.Condition.VISIT_OCCURRENCE_ID', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CONDITION_SOURCE_VALUE', full_name='cdmv5.Condition.CONDITION_SOURCE_VALUE', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CONDITION_SOURCE_CONCEPT_ID', full_name='cdmv5.Condition.CONDITION_SOURCE_CONCEPT_ID', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=349,
)


_DRUGEXPOSURE = _descriptor.Descriptor(
  name='DrugExposure',
  full_name='cdmv5.DrugExposure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DRUG_EXPOSURE_ID', full_name='cdmv5.DrugExposure.DRUG_EXPOSURE_ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=391,
)


_PROCEDURE = _descriptor.Descriptor(
  name='Procedure',
  full_name='cdmv5.Procedure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=404,
)


_VISIT = _descriptor.Descriptor(
  name='Visit',
  full_name='cdmv5.Visit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VISIT_OCCURRENCE_ID', full_name='cdmv5.Visit.VISIT_OCCURRENCE_ID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drugs', full_name='cdmv5.Visit.drugs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='conditions', full_name='cdmv5.Visit.conditions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='procedures', full_name='cdmv5.Visit.procedures', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=555,
)


_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='cdmv5.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='person_id', full_name='cdmv5.Person.person_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='year_of_birth', full_name='cdmv5.Person.year_of_birth', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='month_of_birth', full_name='cdmv5.Person.month_of_birth', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='day_of_birth', full_name='cdmv5.Person.day_of_birth', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_of_birth', full_name='cdmv5.Person.time_of_birth', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='race', full_name='cdmv5.Person.race', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='cdmv5.Person.gender', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ethnicity', full_name='cdmv5.Person.ethnicity', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location_id', full_name='cdmv5.Person.location_id', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='provider_id', full_name='cdmv5.Person.provider_id', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='care_site_id', full_name='cdmv5.Person.care_site_id', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender_source_value', full_name='cdmv5.Person.gender_source_value', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender_source_concept_id', full_name='cdmv5.Person.gender_source_concept_id', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='race_source_value', full_name='cdmv5.Person.race_source_value', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='race_source_concept_id', full_name='cdmv5.Person.race_source_concept_id', index=14,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ethnicity_source_concept_id', full_name='cdmv5.Person.ethnicity_source_concept_id', index=15,
      number=16, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ethnicity_source_value', full_name='cdmv5.Person.ethnicity_source_value', index=16,
      number=17, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='person_source_value', full_name='cdmv5.Person.person_source_value', index=17,
      number=18, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visits', full_name='cdmv5.Person.visits', index=18,
      number=19, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=1040,
)

_VISIT.fields_by_name['drugs'].message_type = _DRUGEXPOSURE
_VISIT.fields_by_name['conditions'].message_type = _CONDITION
_VISIT.fields_by_name['procedures'].message_type = _PROCEDURE
_PERSON.fields_by_name['visits'].message_type = _VISIT
DESCRIPTOR.message_types_by_name['Condition'] = _CONDITION
DESCRIPTOR.message_types_by_name['DrugExposure'] = _DRUGEXPOSURE
DESCRIPTOR.message_types_by_name['Procedure'] = _PROCEDURE
DESCRIPTOR.message_types_by_name['Visit'] = _VISIT
DESCRIPTOR.message_types_by_name['Person'] = _PERSON

Condition = _reflection.GeneratedProtocolMessageType('Condition', (_message.Message,), dict(
  DESCRIPTOR = _CONDITION,
  __module__ = 'ohdsi_pb2'
  # @@protoc_insertion_point(class_scope:cdmv5.Condition)
  ))
_sym_db.RegisterMessage(Condition)

DrugExposure = _reflection.GeneratedProtocolMessageType('DrugExposure', (_message.Message,), dict(
  DESCRIPTOR = _DRUGEXPOSURE,
  __module__ = 'ohdsi_pb2'
  # @@protoc_insertion_point(class_scope:cdmv5.DrugExposure)
  ))
_sym_db.RegisterMessage(DrugExposure)

Procedure = _reflection.GeneratedProtocolMessageType('Procedure', (_message.Message,), dict(
  DESCRIPTOR = _PROCEDURE,
  __module__ = 'ohdsi_pb2'
  # @@protoc_insertion_point(class_scope:cdmv5.Procedure)
  ))
_sym_db.RegisterMessage(Procedure)

Visit = _reflection.GeneratedProtocolMessageType('Visit', (_message.Message,), dict(
  DESCRIPTOR = _VISIT,
  __module__ = 'ohdsi_pb2'
  # @@protoc_insertion_point(class_scope:cdmv5.Visit)
  ))
_sym_db.RegisterMessage(Visit)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'ohdsi_pb2'
  # @@protoc_insertion_point(class_scope:cdmv5.Person)
  ))
_sym_db.RegisterMessage(Person)


# @@protoc_insertion_point(module_scope)
